### ISSUE TITLE
TypeError: 'ChannelParticipants' object is not subscriptable

### ISSUE THREAD

**Issue by ljhOfGithub** [edogab33/telegram-groups-crawler#3]
complete error is:
```Traceback (most recent call last):
  File "scraper.py", line 370, in <module>
    client.loop.run_until_complete(main())
  File "/root/.miniconda3/envs/python38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "scraper.py", line 41, in main
    await init_empty()
  File "scraper.py", line 197, in init_empty
    groups.append(await collect_data(dialog, ""))
  File "scraper.py", line 253, in collect_data
    async for m in client.iter_participants(dialog.id):
  File "/root/.miniconda3/envs/python38/lib/python3.8/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/root/.miniconda3/envs/python38/lib/python3.8/site-packages/telethon/client/chats.py", line 224, in _load_next_chunk
    participants = results[i]
TypeError: 'ChannelParticipants' object is not subscriptable```
The same issue also happens in Telethon:[https://github.com/LonamiWebs/Telethon/issues/3787](url)
Can change the version of telethon work?Thank you.

**Comment by edogab33** [comment]
How can I replicate the error? Is it a group or a channel? How many members?

However it seems an error given by a bug in Telethon, but this part of the code definitely need more documentation.

**Comment by ljhOfGithub** [comment]
> How can I replicate the error? Is it a group or a channel? How many members?
> 
> However it seems an error given by a bug in Telethon, but this part of the code definitely need more documentation.

We are researching how to identify scam messages in telegram,the group name is t.me/bitshibatoken，and it has more than 31,000 members.

**Comment by edogab33** [comment]
> > How can I replicate the error? Is it a group or a channel? How many members?
> 
> > 
> 
> > However it seems an error given by a bug in Telethon, but this part of the code definitely need more documentation.
> 
> 
> 
> We are researching how to identify scam messages in telegram,the group name is t.me/bitshibatoken，and it has more than 31,000 members.

I am sorry for the delay.

I was not sure about the source of this problem because I believe that when I was intensively using this script I also encountered this bug. But my memory is not good enough.

My assumption is that this happens when you try to interact with legacy groups which are not supported by the APIs anymore.

Indeed, in the official repository other users are reporting the same problem: [read here](https://github.com/LonamiWebs/Telethon/issues/3787#issuecomment-1100683630)
