### ISSUE TITLE
May i ask: how to merge the old files with the new ones

### ISSUE THREAD

**Issue by caixinminnihao** [edogab33/telegram-groups-crawler#5]
following you step, i have generate file named 'groups2', can you guide me how to merge?
another, if i want to join some group, how to do?
thank you anyway

**Comment by edogab33** [comment]
Hi, 

To merge data about groups just load the files with pandas and merge them. Refer to the documentation!

About joining the groups, my code already does it (and after storing all the messages it leaves). So, what do you mean?

Thanks :)
