### ISSUE TITLE
used the code recently?

### ISSUE THREAD

**Issue by mrborhani** [edogab33/telegram-groups-crawler#6]
i wrote a python scrawler too but didn't worked , first i used a real account to grab and then post target data to my channel but my number got banned, after that i made some changes it grabs data from some channels (real account inserted) and sends them to a robot for posting them to my channel and with this way another number got banned too, i just wanted 3 channels posts not much, I don't know what to do, does your script still work then i use yours?

**Comment by edogab33** [comment]
I don't know if the script still works, but that's a common issue. However, back when I was using it, I used to run it in parallel with 10 accounts and none of them have been banned.
